services:
  db:
    image: postgres:18
    environment:
      - POSTGRES_DB=pastedb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  sut:
    build: .
    depends_on:
      - db
    environment:
      - PORT=8000
    secrets:
      - source: pbnh.yaml
        target: /etc/pbnh.yaml
  tests:
    build:
      context: .
      target: test
    depends_on:
      - sut
    secrets:
      - pbnh.yaml
    environment:
      - PBNH_CONFIG=/run/secrets/pbnh.yaml
secrets:
  pbnh.yaml:
    file: ./tests/pbnh.yaml
